version: 1.0.{build}
clone_folder: c:\projects\srp.net
image: Visual Studio 2017

install:
- git submodule update --init --recursive

before_build:
- nuget restore src\srp.sln
- choco install opencover.portable
- choco install codecov

build:
  project: src\srp.sln
  parallel: true
  verbosity: minimal

before_test:
- where vstest.console
- where nunit-console.exe

test_script: 
- vstest.console.exe /logger:Appveyor C:\projects\srp.net\src\srp.tests\bin\Debug\net35\srp.tests.dll
- OpenCover.Console.exe -returntargetcode -register:administrator -target:"vstest.console.exe" -targetargs:"/logger:Appveyor C:\projects\srp.net\src\srp.tests\bin\Debug\net461\srp.tests.dll" -filter:"+[*]* -[MemoDb]*" -output:".\srp.net461.xml"
- OpenCover.Console.exe -returntargetcode -register:administrator -target:"vstest.console.exe" -targetargs:"/logger:Appveyor C:\projects\srp.net\src\srp.tests\bin\Debug\netcoreapp1.0\srp.tests.dll" -output:".\srp.netcore10.xml"
#- OpenCover.Console.exe -returntargetcode -register:administrator -safemode:off -target:"vstest.console.exe" -targetargs:"/logger:Appveyor C:\projects\srp.net\src\srp.tests\bin\Debug\netcoreapp2.0\srp.tests.dll" -output:".\srp.netcore20.xml"
- vstest.console.exe /logger:Appveyor C:\projects\srp.net\src\srp.tests\bin\Debug\netcoreapp2.0\srp.tests.dll

after_test:
- codecov -f "srp.net461.xml"
- codecov -f "srp.netcore10.xml"
#- codecov -f "srp.netcore20.xml"
